sudo: required
services:
  - docker

before_install:
  - docker build -t bryanchoi/docker-react -f Dockerfile.dev .

script:
  - docker run bryanchoi/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-298649183257'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
